export default function () {
  return {
    list_of_raws: [
      { id: "7", description: "acém bovino", thumbnail: 'acem_bovino.png'  },
      { id: "33", description: "açúcar mascavo", thumbnail: 'acucar_mascavo.jpg'  },
      { id: "34", description: "água", thumbnail: 'agua.jpg'  },
      { id: "68", description: "alecrim", thumbnail: 'alecrim.jpg'  },
      { id: "27", description: "alho", thumbnail: 'alho.jpg'  },
      { id: "58", description: "alho porró", thumbnail: 'alho_porro.jpg'  },
      { id: "65", description: "amido de milho", thumbnail: 'amido.jpg'  },
      { id: "35", description: "anis estrelado", thumbnail: 'anis_estrelado.png'  },
      { id: "13", description: "antioxidante (Eritorbato de Sódio - INS 316)" , thumbnail: 'sal.jpg'  },
      { id: "38", description: "apara suína", thumbnail: 'apara_suina.jpg' },
      { id: "66", description: "bicarbonato de sódio", thumbnail: 'bicarbonato.jpg' },
      { id: "29", description: "canela", thumbnail: 'canela.jpg' },
      { id: "63", description: "carne bovina magra", thumbnail: 'carne_bovina_magra.jpg' },
      { id: "62", description: "cardamomo", thumbnail: 'cardamomo.jpg' },
      { id: "41", description: "cebola", thumbnail: 'cebola.jpg' },
      { id: "78", description: "cebolinha", thumbnail: 'cebolinha.jpg' },
      { id: "52", description: "colorau", thumbnail: 'colorau.jpg' },
      { id: "32", description: "cominho", thumbnail: 'cominho.jpg'  },
      { id: "3", description: "copa Lombo", thumbnail: 'copa_suina.jpg' },
      { id: "47", description: "corante carmin líquido", thumbnail: 'corante_carmin.jpg' },
      { id: "73", description: "coxa de frango", thumbnail: 'coxa_de_frango.jpg' },
      { id: "8", description: "coxão mole suíno", thumbnail: 'coxao_mole_suino.jpg'  },
      { id: "50", description: "cravo da índia", thumbnail: 'cravo_da_india.jpg' },
      { id: "42", description: "cultura SBM11", thumbnail: 'sbm11.jpg' },
      { id: "81", description: "cultura T-SPX", thumbnail: 'tspx.jpg' },
      { id: "10", description: "cura #1, 7% de nitrato", thumbnail: 'sal_de_cura.jpg' },
      { id: "11", description: "cura #2, 6% de nitrato", thumbnail: 'sal_de_cura.jpg'  },
      { id: "43", description: "dextrose", thumbnail: 'dextrose.jpg' },
      { id: "14", description: "emulsificante (Tripolifostato de sódio )", thumbnail: 'sal.jpg'  },
      { id: "28", description: "erva doce", thumbnail: 'erva_doce.jpg'  },
      { id: "83", description: "fígado bovino", thumbnail: 'figado_bovino.jpg'  },
      { id: "84", description: "fígado suíno", thumbnail: 'figado_suino.jpg'  },
      { id: "21", description: "filme Colágeno, largura 210mm", thumbnail: 'filme_colageno.png' },
      { id: "67", description: "fondor, tempero pronto", thumbnail: 'fondor.jpg' },
      { id: "72", description: "fubá", thumbnail: 'fuba.jpg' },
      { id: "82", description: "Fumaça líquida", thumbnail: 'fumaca_liquida.png' },
      { id: "45", description: "gelo", thumbnail: 'gelo.png' },
      { id: "64", description: "gengibre", thumbnail: 'gengibre.jpg' },
      { id: "51", description: "glutamato monosódico", thumbnail: 'glutamato.jpg' },
      { id: "6", description: "gordura de lombo", thumbnail: 'gordura_suina.jpg' },
      { id: "49", description: "joelho suíno", thumbnail: 'joelho_suino.png' },
      { id: "56", description: "kummel", thumbnail: 'kummel.jpg' },
      { id: "80", description: "leite em pó desnatado", thumbnail: 'leite_em_po.jpg' },
      { id: "59", description: "ligatari", thumbnail: 'ligatari.jpg'  },
      { id: "5", description: "lombo Suíno", thumbnail: 'lombo_suino.jpg' },
      { id: "40", description: "louro", thumbnail: 'louro.jpg' },
      { id: "85", description: "manjerona", thumbnail: 'manjerona.jpg' },
      { id: "31", description: "mostarda", thumbnail: 'nos_mostarda.jpg'  },
      { id: "30", description: "noz moscada", thumbnail: 'noz_moscada.jpg'  },
      { id: "86", description: "oregano", thumbnail: 'oregano.jpg'  },
      { id: "2", description: "paleta Suína", thumbnail: 'paleta_suina.jpg' },
      { id: "4", description: "pancetta", thumbnail: 'pancetta_suina.jpg' },
      { id: "55", description: "páprica defumada", thumbnail: 'paprica.jpg' },
      { id: "53", description: "páprica doce", thumbnail: 'paprica.jpg' },
      { id: "54", description: "páprica picante", thumbnail: 'paprica.jpg' },
      { id: "9", description: "patinho suíno", thumbnail: 'patinho_suino.jpg' },
      { id: "36", description: "pele suína (couro)", thumbnail: 'pele_suina.png' },
      { id: "26", description: "pimenta calabresa", thumbnail: 'pimenta_calabresa.jpg'  },
      { id: "61", description: "pimenta dedo de moça", thumbnail: 'pimenta_dedo_moca.jpg'  },
      { id: "25", description: "pimenta do reino", thumbnail: 'pimenta_do_reino.jpg'  },
      { id: "71", description: "pimenta do reino branca", thumbnail: 'pimenta_do_reino_branca.jpg'  },
      { id: "79", description: "peito de frango", thumbnail: 'peito_de_frango.jpg'  },
      { id: "1", description: "pernil Suíno", thumbnail: 'pernil_suino.png' },
      { id: "60", description: "proteína de soja", thumbnail: 'proteina_soja.jpg'},
      { id: "75", description: "queijo mussarela", thumbnail: 'mussarela.jpg'},
      { id: "76", description: "queijo provolone", thumbnail: 'provolone.jpg'},
      { id: "77", description: "queijo coalho", thumbnail: 'queijo_coalho.jpg'},
      { id: "23", description: "rede elástica, 50mm", thumbnail: 'rede_elastica.jpg' },
      { id: "22", description: "rede elástica, 65mm", thumbnail: 'rede_elastica.jpg'  },
      { id: "24", description: "rede elástica, 130mm", thumbnail: 'rede_elastica.jpg'  },
      { id: "12", description: "sal comum", thumbnail: 'sal.jpg'  },
      { id: "48", description: "salmoura para cura líquida", thumbnail: 'salmoura.jpg' },
      { id: "39", description: "salsinha", thumbnail: 'salsinha.jpg' },
      { id: "44", description: "semente de coentro", thumbnail: 'semente_coentro.jpg' },
      { id: "74", description: "sobre coxa de frango", thumbnail: 'sobre_coxa_frango.png' },
      { id: "87", description: "tomate", thumbnail: 'tomate.png' },
      { id: "88", description: "tomate seco", thumbnail: 'tomate_seco.jpg' },
      { id: "37", description: "toucinho", thumbnail: 'toucinho.png' },
      { id: "69", description: "tomilho", thumbnail: 'tomilho.jpg' },
      { id: "16", description: "tripa Suína, calibre 22/24" },
      { id: "17", description: "tripa Suína, calibre 24/26" },
      { id: "15", description: "tripa Suína, calibre 28/32" },
      { id: "18", description: "tripa Colágeno, calibre 40" },
      { id: "19", description: "tripa Colágeno, calibre 50" },
      { id: "20", description: "tripa Colágeno, calibre 70" },
      { id: "46", description: "vinho tinto seco", thumbnail: 'vinho_tinto.jpg' },
      { id: "70", description: "vinho branco", thumbnail: 'vinho_branco.jpg' },
    ]
  }; 
}
